# Generated by Django 6.0.1 on 2026-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sms_template',
            field=models.TextField(default='Hello {name}, your ticket for {event} is confirmed. code: {code}'),
        ),
    ]
