# Generated by Django 6.0.1 on 2026-01-24 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_code', models.CharField(max_length=8, unique=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
