# Generated by Django 6.0.1 on 2026-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        ('tickets', '0003_add_checked_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numeric_code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numeric_code'], name='tickets_tic_numeric_579f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_checked_in'], name='tickets_tic_is_chec_281b56_idx'),
        ),
    ]
