# Generated by Django 6.0.1 on 2026-01-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        ('tickets', '0004_alter_ticket_numeric_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_numeric_579f1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_is_chec_281b56_idx',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('event', 'attendee'), name='unique_ticket_per_event_attendee'),
        ),
    ]
