# Generated by Django 6.0.1 on 2026-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        ('tickets', '0005_remove_ticket_tickets_tic_numeric_579f1f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numeric_code'], name='tickets_tic_numeric_579f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_checked_in'], name='tickets_tic_is_chec_281b56_idx'),
        ),
    ]
