# Generated by Django 6.0.1 on 2026-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_ticket',
            field=models.FileField(blank=True, upload_to='pdf_tickets/'),
        ),
    ]
