# Generated by Django 6.0.1 on 2026-01-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_pdf_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='qr_image',
            new_name='qr_code_image',
        ),
    ]
