# Generated by Django 6.0.1 on 2026-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(default=255700000000, max_length=15),
            preserve_default=False,
        ),
    ]
